### ISSUE TITLE
[EPIC] Tips / Suggestions 

### ISSUE THREAD

**Issue by nicolastudela** [nicolastudela/calacabana#42]

**Comment by nicolastudela** [comment]
On the booking page, we could show a banner encouraging users to book the apartment or either choose a better option

Tasks:

- [ ] [Create Message banner](https://github.com/nicolastudela/calacabana/issues/32)
- [ ] Create API that returns suggestions given an apartment and datePeriod
- [ ] Connect both things
