### ISSUE TITLE
[SEO] Review and fill SEO meta-tags

### ISSUE THREAD

**Issue by nicolastudela** [nicolastudela/calacabana#55]

**Comment by nicolastudela** [comment]
TaskList retrieved from this article: https://www.searchenginejournal.com/important-tags-seo/156440/#close

- [ ] Meta-Title 
- [ ] Meta-Description
- [ ] Review Headings
- [X] image alt-attributes
- [ ] NoFollow attributes
- [ ] Robots meta tags
- [ ] rel="canonical" link tag
- [ ] schema Markup
- [ ] social media meta tags
- [] viewport meta tags

**Comment by nicolastudela** [comment]
fill Schema Markup -> https://hallanalysis.com/json-ld-generator/
