### ISSUE TITLE
[EPIC] [book-page] Create book page. 

### ISSUE THREAD

**Issue by nicolastudela** [nicolastudela/calacabana#6]
**Page path:** 
"/book/[apt]?check_in={checkin}&check_out={checkout}" 

**Flows on different inputs:**

1)  Page called without apartment [apt] or empty => Show general error on page  => #25 
2) Valid Apartment param:
2a) Invalid dates (not existent, not valid booking date) => Redirects to /aparment/[apt]
2b) Valid Date but period already taken. Sets the page prop error to subseccions "already booked error status" => #26
2c) Happy Path alll sections should be visible and without errors

// TODO 
- Think flow after valid Contact-us action

Dependencies:
- [X] #29 [book-page] Create Page Layout
- [X] #30 [book-page] Create Apartment Details Preview
- [X] #31 [book-page] Create Trip section 
- [X] #27 [book-page] Create Contact-us seccion.
- [X] #28 [API] Create contact-us/pre-book API.
- [X] #26 [book-page] Booking page with invalid dates. Create a general component to show on sections when not valid 
- [X] #40 Draft-Deploy. Initial setup
- [X] #41 [API] contact: send 2 emails (info@calabana.com & client) about the contact
