### ISSUE TITLE
[EPIC] Agregar Video en Home y cada pagina de apartamento

### ISSUE THREAD

**Issue by nicolastudela** [nicolastudela/calacabana#91]
- [ ] spike on maneras de incluir videos sin afectar perfomance
- [ ] incluir video en paginas de apartamentos
- [ ] incluir video en home page
